name = "Hugobricks-Mod"
license = "MIT"
licenselink = "https://github.com/rterakedis/hugobricks-mod/LICENSE.md"
description = "The Hugobricks theme, but in module form."
homepage = "https://github.com/rterakedis/hugobricks-mod/"
demosite = "https://neonmirrors.net/"
min_version = "0.128.0"

# If the theme has multiple authors
authors = [
  {name = "Joost van der Schee", homepage = "https://github.com/jhvanderschee/hugobricks"},
  {name = "Rob Terakedis", homepage = "https://github.com/rterakedis/hugobricks-mod"},
]